### ISSUE TITLE
How to report bugs and request features

### ISSUE THREAD

**Issue by BeanstreamDeveloper** [bambora-na/beanstream-java#1]
Welcome to the Beanstream Java SDK issue tracker and forum. Feel free to use this space for discussions, bug reporting, requesting new features, or for asking questions.

Be polite and professional and post what questions you have. Use appropriate tags so your inquiries get filtered to the right people.

**Comment by dunnett** [comment]
In the routine HttpsConnector there is a line that says:
 
String auth = Base64.encode((merchantId + ":" + apiPasscode).getBytes());
 
This returns a Base64 encoded string of the merchant id and api passcode. Unfortunately in some Java implementations it also has a newline character appended on the end of the string. When this string is added as an HTTP header:
 
http.addHeader("Authorization", "Passcode " + auth);
 
the newline character is not stripped. When the org.apache.http.client code transmits this header it also transmits the newline character. The HTTP protocol specifies that the end of the header section is identified by a blank line, so as soon as the Authorization header is transmitted the server receiving the request stops processing headers and treats the rest of the transmission as data. This means that what the Beanstream server sees as “data” includes some of the header information, which apparently confuses it to the point where it throws up its hands and returns a meaningless error message about "Invalid Hostname".
 
The solution is to simply add a .trim() to the line that builds the auth string:
 
String auth = Base64.encode((merchantId + ":" + apiPasscode).getBytes().trim();

**Comment by BeanstreamDeveloper** [comment]
Thanks @dunnett 
I'll add the trim() to the base64 encode. Annoying that it can automatically append a newline.
