### ISSUE TITLE
Code Bounties Open!

### ISSUE THREAD

**Issue by BeanstreamDeveloper** [bambora-na/beanstream-java#2]
If you would like to help out on this SDK project and earn some money at the same time, let us know! We have $1500 to give away for some very easy tasks that will fill out this SDK with the rest of the API features.
Sign up at [this page](http://developer.beanstream.com/beanstream-java-sdk-code-bounty-challenge/) or let us know in this thread if you are interested. These are the API tasks that are available:
- $200 Tokenization, Cash, Cheque
- $150 Returns
- $150 Voids
- $150 Pre-authorized Completions
- $150 Detailed Exception Handling 

The first round of tasks is available right now, the next 2 rounds will be opening up in September. The other rounds have the remaining $700.

There is a [reference C# implementation](https://github.com/Beanstream-DRWP/beanstream-dotnet) that should be almost copy-paste into Java. I don't foresee each task taking more than a few hours to implement and then another hour to document and test.

**Comment by davidlight77** [comment]
No longer a thing
