### ISSUE TITLE
Is there a new Java API released for Bambora (NEW) instead of the Beanstream (OLD)

### ISSUE THREAD

**Issue by kevzlou7979** [bambora-na/beanstream-java#6]
Hi there,

With the migration of the Javascript API's which is from Beanstream Payfields -> Bambora Checkout Fields. Is there a plan to migrate this ` beansream-java ` to `bambora-java `? Or is that already developed.

Best Regards,
Mark

**Comment by pzelnip** [comment]
Hi, there are currently no plans to migrate this at this time.  Thanks.
